### ISSUE TITLE
files

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fake-api#28]
Our goal is to start to generate some files for fetch plugin.
And instead of keeping some files like users.json, favorites.json - we'll generate them on the fly.
Why we're doing it here? because it's a save place where we can play.
so, how the logic works. When user open one route(it can be any new route).
- You should read data from file from sd-wrapper(you don't need fetch at that point).
- That data should have array or object type(google `type_of`)
- Then put that data into a new file(keep in mind that we'll do it with different filenames later, so don't hardcode it)
- That file should appear on your local project folder.

And when we'll test it here - we'll move that functionality to groceristar-fetch

https://dev.to/mrm8488/from-callbacks-to-fspromises-to-handle-the-file-system-in-nodejs-56p2
https://stackoverflow.com/questions/43622337/using-import-fs-from-fs
https://medium.com/@ilonacodes/front-end-shorts-how-to-read-content-from-the-file-input-in-react-17f49b293909

**Comment by atherdon** [comment]
ok, cool - this is important task for both of us!
let's kick his ass

**Comment by vadim9999** [comment]
@atherdon if I make this 
'''
const {users} = require('@sd-wrapped')
'''
Variable users will be containing an object. How can I get just path to file that is in another module?

**Comment by atherdon** [comment]
you question appeared only because you didn't work on the split process for two files.
you can see how we included files at `fetch` plugin - https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GroceriStar/files.js

**Comment by atherdon** [comment]
and i think we have something, related to raw paths... Why do you need a whole path to users file?
if you creating another file - you can keep it in the root of our server - right now it's not important. later we'll deal with saving files at some folders... right now my goal is no understand that we can save files by using commands from expressjs server

**Comment by atherdon** [comment]
if you need a path only - you can extend the functionality of sd-wrapper easily. that code is very simple

**Comment by vadim9999** [comment]
>You should read data from file from sd-wrapper(you don't need fetch at that point).

I just should get data by method or read from file by using expressjs?

**Comment by atherdon** [comment]
our goal is: i want to get rid of files, that can be created in a
programmable way.
so, first of all, we'll replace files like favorites, items, etc - because
if we'll change some of our structures - we'll need to update those files.
So i think you can grab data from sd-wrapper without any methods. But if
you think that you need methods from fetch - please use them
Because i didn't dig a lot at this task and can be mistaken

>

**Comment by atherdon** [comment]
by my plan - when you'll complete this task and we'll have that code -
we'll move it inside of sd-wrapper. So some files will be static(as right
now) and small files will be generated at `build` script. Then sd-wrapper
will be published and connected to `groceristar-fetch`. So it's better to
not use fetch methods

>

**Comment by vadim9999** [comment]
It's task is done?

**Comment by atherdon** [comment]
I don't know - i didn't check it. tell me how i can test it locally?

**Comment by atherdon** [comment]
just for quick test - can you try to save few other structures? i think it works, but you now me - always want to recheck it.
As i see: you saved a `users.json` file...

**Comment by atherdon** [comment]
maybe test.txt and test1.json was created programmatically too

**Comment by atherdon** [comment]
quick question: "That data should have array or object type(google type_of)" - you did it, right?

**Comment by vadim9999** [comment]
Object -> stringify - > write in file

**Comment by atherdon** [comment]
ok got it, let's jump to #102 and add please check for `type of` stuff before saving data in your file. and before stringify too...

**Comment by atherdon** [comment]
and then i'll close this task

**Comment by atherdon** [comment]
closing it. looks good
