### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/fake-api#29]
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:4000/grocery/data/2 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by atherdon** [comment]
is it critical?
i mean yep, we can address that, but i think the first and the main reason why this is happens, because you have both local nodejs server up and local react setup

**Comment by atherdon** [comment]
i mean this was the first reasons why we should have server on heroku active and automatically deployed after each commit

**Comment by atherdon** [comment]
so i'll advice you to work on projects separately. like if you work on routes at nodejs server - then run it locally. if you need to grab data into react project - then launch it only and use an outside url from heroku

**Comment by atherdon** [comment]
i also think that maybe it can be solved by adding some settings, but again - it not buzzing me very well. but if you want to dig into it - i'm ok to give you this option to figure it out by yourself

**Comment by vadim9999** [comment]
This problem also appear when I change url from localhost on heroku. this bug is on two methods

**Comment by atherdon** [comment]
links:

https://github.com/axios/axios/issues/853#issuecomment-351554276
https://enable-cors.org/server_expressjs.html
https://enable-cors.org/server_expressjs.html

https://medium.com/@nabil6391/avoid-cors-requests-for-a-react-app-2988e0061c1a

https://expressjs.com/en/resources/middleware/cors.html
https://stackoverflow.com/a/8572637

**Comment by atherdon** [comment]
i'm sure you'll handle that

**Comment by vadim9999** [comment]
I think we can close this issue

**Comment by atherdon** [comment]
perfect!
