### ISSUE TITLE
different "projects" have different starting endpoints at routes

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fake-api#33]
aka if we have method, related to GS - we have a main url "/groceristar"
and sub-routes - "/groceristar\sub-method-name"

**Comment by atherdon** [comment]
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#Defining_and_using_separate_route_modules

**Comment by vadim9999** [comment]
It's task complete? or can you give me more details what should I do?

**Comment by atherdon** [comment]
only if you can confirm that CK methods(routes) are 100% separated from GS routes.
like each of CK routes starts from `ck`(example: `/ck/get-five-random-recipes`) and GS routes starts with `gs` i think it'll be done

**Comment by atherdon** [comment]
btw, if you want a quick turnaround with sd-wrapper - you can connect to those files without using `fetch` plugin. I install to fake-api `sd-wrapper` so you'll be able to connect to our static files, avoiding the fetch.
And yeah, we change 'lib' folder to 'dist' because this is how major players doing it...

**Comment by vadim9999** [comment]
doesn't work. Ok I just copy and paste folder dist from sd-wrapper into node modules in fake-api

**Comment by atherdon** [comment]
nope, it's not good way... let's wait then, jump into another task please.
We can easily fix it, but i want to use other hands for this task...

**Comment by vadim9999** [comment]
Ok

**Comment by vadim9999** [comment]
In PR https://github.com/GroceriStar/fake-api/pull/58
