### ISSUE TITLE
find out why build is crashing right now

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fake-api#84]
let's start with this task. @MohnnadBahaa 
We need to find trouble and discuss our plan to solve it
https://travis-ci.org/GroceriStar/fake-api/builds/510193244

**Comment by MohnnadBahaa** [comment]
i follow the steps but when  i follow the steps 
run npm test it does not let me see what the errors 

![1](https://user-images.githubusercontent.com/28856488/55268200-a1870d80-5298-11e9-80cb-7805bd4c5a87.PNG)
![2](https://user-images.githubusercontent.com/28856488/55268202-a1870d80-5298-11e9-8f8c-79afda3b8c25.png)

**Comment by MohnnadBahaa** [comment]
and actually i changed the command from NODE_ENV=TEST to set NODE_ENV=TEST

**Comment by atherdon** [comment]
@vadim9999

**Comment by atherdon** [comment]
can you grab the latest changes, reinstall packages and try again
?

**Comment by vadim9999** [comment]
On my PC tests working fine
![2019-03-31-103336_1280x1000_scrot](https://user-images.githubusercontent.com/35640573/55286170-89021a80-53a0-11e9-99bc-a7868d87bb47.png)

**Comment by MohnnadBahaa** [comment]
thank you , i solved the issue
i should install node -env global "npm install -g win-node-env"
this issue just with windows.

Best Regards,

Mohannad Bahaa Al-Musa | Full Stack Software Engineer
| phone: +962786866609
| email: mohbah026@gmail.com

keep in touch :
<https://twitter.com/bahaa_mohannad>
<https://www.linkedin.com/in/mohannad-bahaa-88984a135/>
<https://github.com/MohnnadBahaa>
<https://angel.co/mohannad-bahaa-al-musa?al_content=current+user+name&al_source=transaction_feed%2Fnetwork_sidebar>

**Comment by atherdon** [comment]
yeah, i also tested on windows and as usually - this OS have their own
rules.
Actually, if we want to make it better and working similar on few major
OS(i'm not sure if we need it - because when this project will be finished
- we'll deploy it on linux server).. But we can do it.
If someone will create a separated task for this - i'll explain a way how
to make expressjs work fine.

I also making some changes in our `fetch` plugin and it still working not
ideal. but hope i'll solve it soon

>

**Comment by atherdon** [comment]
sp, what is our result here?

**Comment by MohnnadBahaa** [comment]
now i am following the steps , also the test is working , but to be honest
i do not  know if should i push or not
or what the expected result from this task .
what i understand just make the test work fine then i will go to issue #84.
Best Regards,

Mohannad Bahaa Al-Musa
| Full Stack Software Engineer
| phone: +962786866609
| email: mohbah026@gmail.com

keep in touch :
<https://twitter.com/bahaa_mohannad>
<https://www.linkedin.com/in/mohannad-bahaa-88984a135/>
<https://github.com/MohnnadBahaa>
<https://angel.co/mohannad-bahaa-al-musa?al_content=current+user+name&al_source=transaction_feed%2Fnetwork_sidebar>

**Comment by atherdon** [comment]
yeah, i think i figure out why tests were crashing before. it was our
`gs-fetch` module.
Let's find out what to do next

>

**Comment by atherdon** [comment]
@vadim9999 do you think we need to add more tests here? it may help us in the future. If yes - can you help me and Mohannad about what should be covered by new tests, please?

**Comment by vadim9999** [comment]
I think need tests that will compare data gets from url and sended from server. because HTTP response can be 200 and recieved data will not expected that you think

**Comment by atherdon** [comment]
@MohnnadBahaa can you do it?

**Comment by MohnnadBahaa** [comment]
I think yes I can do it.

**Comment by atherdon** [comment]
awesome! tests are always important - they make me feel save :)

>

**Comment by atherdon** [comment]
and we have new errors in builds: https://travis-ci.org/GroceriStar/fake-api/jobs/515551950

**Comment by atherdon** [comment]
@MohnnadBahaa all is fine? don't see your activity here...
